/**
 * Ingestion-matching transformer differential harness — migration side.
 * (Drill migration overhaul item D4, https://github.com/Countly/migration/issues/6)
 *
 * Asserts that this repo's transform (src/transform/normalize.ts) reproduces,
 * for every document in the shared fixture corpus, EXACTLY the canonical
 * ClickHouse row that countly-platform's live ingestion normalization
 * produces (checked-in goldens generated by the platform repo).
 *
 * The fixture set (corpus.json, goldens.json, decode.mjs, canonicalize.mjs)
 * is vendored byte-identical from countly-platform
 * test/unit/fixtures/drill-transform-differential/. The goldens' embedded
 * hashes tie the three artifacts together, so a partial sync fails loudly.
 *
 * If this test fails:
 *  - after a change in THIS repo: the migration transform drifted from live
 *    ingestion — fix the transform, do not touch the goldens here.
 *  - after syncing new fixtures from countly-platform: the platform changed
 *    normalization behavior — align src/transform/ to match.
 *
 * Pure unit test: no MongoDB/ClickHouse/Redis needed.
 */

import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// eslint-disable-next-line import/no-unresolved
import { decodeDoc } from './decode.mjs';
// eslint-disable-next-line import/no-unresolved
import { canonicalizeOutput } from './canonicalize.mjs';
import { transformDocument, transformBatch, type SourceDocument } from '../../src/transform/normalize.ts';
import { SkipCounter } from '../../src/transform/skip-reasons.ts';

const here = path.dirname(fileURLToPath(import.meta.url));

const corpus = JSON.parse(readFileSync(path.join(here, 'corpus.json'), 'utf8')) as {
  entries: Array<{ id: string; group: string; notes: string; doc: Record<string, unknown> }>;
};
const goldens = JSON.parse(readFileSync(path.join(here, 'goldens.json'), 'utf8')) as {
  corpusSha256: string;
  contractSha256: string;
  entries: Record<string, { skip?: true; row?: Record<string, unknown> }>;
};

function fileSha256(fileName: string): string {
  return createHash('sha256').update(readFileSync(path.join(here, fileName))).digest('hex');
}

describe('differential: migration transform vs countly-platform live ingestion', () => {
  it('vendored fixture set is in sync (corpus matches the goldens generation)', () => {
    expect(fileSha256('corpus.json'), 'corpus.json does not match the corpus the goldens were generated from — re-sync ALL fixture files from countly-platform test/unit/fixtures/drill-transform-differential/').toBe(goldens.corpusSha256);
    const contractSha = createHash('sha256')
      .update(readFileSync(path.join(here, 'decode.mjs')))
      .update(readFileSync(path.join(here, 'canonicalize.mjs')))
      .digest('hex');
    expect(contractSha, 'decode.mjs/canonicalize.mjs do not match the contract the goldens were generated with — re-sync ALL fixture files from countly-platform').toBe(goldens.contractSha256);
  });

  it('every corpus fixture has a golden and vice versa', () => {
    const corpusIds = corpus.entries.map((entry) => entry.id).sort();
    expect(Object.keys(goldens.entries).sort()).toEqual(corpusIds);
  });

  for (const entry of corpus.entries) {
    it(`reproduces the live-ingestion row for "${entry.id}" (${entry.group})`, () => {
      const golden = goldens.entries[entry.id];
      const result = transformDocument(decodeDoc(entry) as SourceDocument);
      const canonical = canonicalizeOutput(result.row);
      expect(canonical, `${entry.notes}\nGoldens are generated by countly-platform live ingestion normalization; fix src/transform/, never the vendored goldens.`).toEqual(golden);
      if ('skip' in golden && golden.skip === true) {
        expect(result.skipReason, 'skipped documents must carry a skip reason').not.toBeNull();
      }
      const serialized = JSON.stringify(canonical);
      expect(serialized).not.toContain('__UNINSERTABLE__');
      expect(serialized).not.toContain('__NONDETERMINISTIC__');
    });
  }

  it('transformBatch matches per-document transformDocument over the whole corpus', () => {
    const docs = corpus.entries.map((entry) => decodeDoc(entry) as SourceDocument);
    const counter = new SkipCounter();
    const { rows } = transformBatch(docs, counter);
    const expectedRows = corpus.entries
      .map((entry) => transformDocument(decodeDoc(entry) as SourceDocument).row)
      .filter((row) => row !== null);
    expect(rows).toEqual(expectedRows);
    expect(rows.length + counter.getTotal()).toBe(corpus.entries.length);
  });
});
